// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xmjazvevavcntmllmcrt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhtamF6dmV2YXZjbnRtbGxtY3J0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc4NDIwODMsImV4cCI6MjA2MzQxODA4M30.e_rU4iX5ixF5KLeXj8El4XYlfr3vUWlEmYRMztcQbis";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);